# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: CC0-1.0
version = 1
SPDX-PackageName = "carbonio-shell-ui"
SPDX-PackageSupplier = "Zextras <https://www.zextras.com>"

[[annotations]]
path = "translations/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = [".idea/**", ".vscode/**", ".husky/**", ".nvmrc", "package.json", "package-lock.json", "tsconfig**.json", "**.iml", "commit.template", "CHANGELOG.md", ".github/**", "THIRDPARTIES", "api-extractor/**", "api-extractor.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "assets/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
